apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-module-20560
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-module-20560
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
